### ISSUE TITLE
Run on windows

### ISSUE THREAD

**Issue by ukos-git** [t-b/igor-pro-vim#1]
I have this running on linux and it works. Taking the same vimrc (and this repo) over to windows breaks syntax highlighting on *ipf files. Manually setting another syntax style works but IgorPro is not listed in the available styles.

I have installed pathogen via vundele's `:PluginInstall` and include this plugin in my vimrc via

`call pathogen#infect('~/Documents/Github/igor-pro-vim/{}')`

**Comment by t-b** [comment]
@ukos-git My config for nvim looks like

```
$ cat ~/.config/nvim/init.vim
set nocompatible
call pathogen#infect('~/projekte/common-orga-and-tools/tools/vim')
call pathogen#helptags()
...
```

and that works with linux and windows.

**Comment by ukos-git** [comment]
Thank you for the hint. I removed the curly brackets and now it works.

```
call pathogen#infect('~/Documents/Github/igor-pro-vim')
```
