### ISSUE TITLE
do not highlight words in <> bracket

### ISSUE THREAD

**Issue by ukos-git** [t-b/igor-pro-vim#5]
![Screenshot from 2019-05-21 11-57-34](https://user-images.githubusercontent.com/16167358/58086909-cc6a4f80-7bbf-11e9-81d2-16d4bf8610b0.png)

**Comment by ukos-git** [comment]
or in general after `#include`

**Comment by t-b** [comment]
@ukos-git Yes it is a bug, but it is also the same behaviour as in IP ;)

**Comment by ukos-git** [comment]
ok. then lets keep it that way until upstream decides to rework its highlighter.
